"""news model

Revision ID: 62c90ce53c54
Revises: a442f48ed347
Create Date: 2025-05-19 12:33:07.543732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c90ce53c54'
down_revision: Union[str, None] = 'a442f48ed347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_uz', sa.String(), nullable=False),
    sa.Column('title_ru', sa.String(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=False),
    sa.Column('photo', sa.String(), nullable=False),
    sa.Column('text_uz', sa.String(), nullable=False),
    sa.Column('text_ru', sa.String(), nullable=False),
    sa.Column('text_en', sa.String(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
