"""apply

Revision ID: ad4f9dd22e2d
Revises: b4b3a7ce5e97
Create Date: 2025-09-10 15:16:23.703789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4f9dd22e2d'
down_revision: Union[str, None] = 'b4b3a7ce5e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applies', sa.Column('time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applies', 'time')
    # ### end Alembic commands ###
