"""logged out

Revision ID: d331b6fa92a9
Revises: 78959d9fd97d
Create Date: 2025-03-12 14:27:23.904303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd331b6fa92a9'
down_revision: Union[str, None] = '78959d9fd97d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_logged_out', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_logged_out')
    # ### end Alembic commands ###
